---
- name: Check if Jenkins service unit folder exists
  ansible.builtin.stat:
    path: "{{ jenkins_init_folder }}"
  register: init_folder_state

- name: Create Jenkins service unit folder, if not exists
  ansible.builtin.file:
    path: "{{ jenkins_init_folder }}"
    state: directory
    mode: 0644
  when: not init_folder_state.stat.exists

- name: Check if Jenkins service unit override config exists
  ansible.builtin.stat:
    path: "{{ jenkins_init_file }}"
  register: init_override_file_state

- name: Create Jenkins service unit override config, if not exists
  ansible.builtin.file:
    path: "{{ jenkins_init_file }}"
    state: touch
    mode: 0644
  when: not init_override_file_state.stat.exists

- name: Update values in service unit override config
  ansible.builtin.lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^Environment="{{ item.option }}"'
    regexp: '^Environment="{{ item.option }}"'
    line: 'Environment="{{ item.option }}={{ item.value }}"'
    state: present
    mode: 0644
  loop: "{{ jenkins_init_options }}"
  register: override_init_config

- name: Create jenkins home directory, if not exists
  ansible.builtin.file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0770
    follow: true

- name: Create folder for custom groovy init scripts
  ansible.builtin.file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

- name: Create directory for storing ssh key
  ansible.builtin.file:
    path: ~/.ssh/jenkins
    state: directory
    owner: root
    group: root
  delegate_to: localhost

- name: Create directory for storing ssh key on remote
  ansible.builtin.file:
    path: "{{ jenkins_home }}/.ssh"
    state: directory
    owner: jenkins
    group: jenkins

- name: Generate an SSH keypair locally
  ansible.builtin.command:
    cmd: ssh-keygen -q -t rsa -b 2048 -f ~/.ssh/jenkins/id_rsa_jenkins_master
    creates: ~/.ssh/jenkins/id_rsa_jenkins_*
  delegate_to: localhost

# TODO: Automate registering agent node using Jenkins CLI
- name: Upload SSH keypair to Jenkins master server
  ansible.builtin.copy:
    src: ~/.ssh/jenkins/
    dest: "{{ jenkins_home }}/.ssh"
    owner: jenkins
    group: jenkins
    mode: 0700

- name: Configure Jenkins default user(s)
  ansible.builtin.template:
    src: basic-security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: jenkins
    group: jenkins
    mode: 0775

- name: Configure Java logging options
  ansible.builtin.template:
    src: logging.properties.j2
    dest: "{{ jenkins_home }}/logging.properties"
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Restart Jenkins service on changes
  ansible.builtin.systemd:
    name: jenkins
    state: restarted
    daemon_reload: true
  when: override_init_config.changed

