---
- name: Import Jenkins GPG key
  ansible.builtin.rpm_key:
    state: "{{ jenkins_gpg_key_state }}"
    key: "{{ jenkins_gpg_key_url }}"
    validate_certs: false

- name: Add Jenkins RedHat-stable repository
  ansible.builtin.get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
    validate_certs: false

- name: Install jenkins
  ansible.builtin.yum:
    name:
      - jenkins
    state: "{{ jenkins_package_state }}"

- ansible.builtin.include_tasks: init.yaml

- name: Start Jenkins
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: "{{ jenkins_start_on_boot }}"
  notify:
  - Remove Jenkins init scripts

- ansible.builtin.include_tasks: plugins.yaml

